name: Release tagged image

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Extract dnsmasq version
        id: dnsmasq
        run: |
          echo "version=$(sed -nr 's/^ARG DNSMASQ_VERSION=(.*)$/\1/p' Dockerfile)" >> "$GITHUB_OUTPUT"
      - name: Extract alpine version
        id: alpine
        run: |
          echo "version=$(grep -oE 'alpine:([^ ]+)' Dockerfile | head -1 | cut -d: -f2)" >> "$GITHUB_OUTPUT"
      - name: Generate tag
        id: tag
        run: |
          echo "bare=${{ steps.dnsmasq.outputs.version }}-alpine${{ steps.alpine.outputs.version }}" >> "$GITHUB_OUTPUT"
          echo "full=${{ steps.dnsmasq.outputs.version }}-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3
      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dnsmasq:v${{ steps.tag.outputs.bare }}
            ghcr.io/${{ github.repository_owner }}/dnsmasq:v${{ steps.tag.outputs.full }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
